### ISSUE TITLE
yarn berry 프리즈마 에러 사항 정리

### ISSUE THREAD

**Issue by PracticeEveryday** [depromeet/13th-4team#4]
# yarn berry 프리즈마 에러 사항

- PrismaClient를 못 불러오는 에러 발생
<img width="563" alt="image" src="https://user-images.githubusercontent.com/97580759/236244901-52341e84-d7c5-4ead-9bac-e3501804a9ac.png">

### 원인
- 프리즈마는 node_modules에 .prisma로 prismaClient를 관리하는 데 yarn berry는 .yarn에 zip 파일로 관리하고 있어 prismaClient를 불러오지 못함
- [contributor 리뷰 yarn berry 지원보다 쿼리에 더 집중하고 싶다고 함.](https://github.com/prisma/prisma/issues/1439#issuecomment-671861692)
    - 2020년에 작성한 거라 조금 오래 됐는데 더 찾아보겠습니다 😢 

### 해결방안
1. ~~prisma를 라이브러리로 생성하여 관리하기~~
- ~~generated를 생성하여 라이브러리로 관리합니다.~~
- ~~CLI `yarn run db:generated`를 실행하면 아래와 같이 prisma 폴더가 생성됩니다.~~
- ~~아래 폴더에서 prismaClient를 가져와서 활용하게 됩니다!~~
<img width="239" alt="image" src="https://user-images.githubusercontent.com/97580759/236252102-7fe8dbd1-231b-40e0-8459-a9e7e4f33e45.png">

- [1번 방법 레퍼런스](https://github.com/prisma/prisma/issues/1439#issuecomment-1023884266)
- [prisma docs](https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/generating-prisma-client)

- 의존성 주입 문제
- generated로 생성된 파일의 의존성 주입이 안 되어 활용하는 방법을 못찾음.
<img width="685" alt="image" src="https://user-images.githubusercontent.com/97580759/236255808-06fb674d-2779-4577-87c3-9a327a351d82.png">

---
2. prisma만 따로 node_modules로 생성하여 관리하기
- [prisma만 unPlugIn 되어 node_modules가 생성됩니다](https://velog.io/@pyo-sh/Yarn-Berry-%ED%99%98%EA%B2%BD%EA%B3%BC-PnP-%EA%B8%B0%EB%8A%A5%EC%97%90%EC%84%9C-Prisma-%EC%82%AC%EC%9A%A9)

---

3. Nestjs + yarn berry + prisma
- 해당 github README에 `Yarn (berry) version 3.1.0 (PnP disabled since it's not supported by NestJs and Prisma yet)` 문구가 있습니다
- 혹시 prisma가 지원되지 않는 걸까요 ㅠㅠㅠ

- [Nestjs + yarn berry + Prisma github Example](https://github.com/alitnk/nestjs-prisma-monorepo#about)

---
- 회의 전까지 더 찾아보고 시도해 보겠습니다 
- 혹시 현 모노레포에서 prisma가 되는 방법을 아신다면 조언 부탁드립니다 ( _ _)

**Comment by JangDaljin** [comment]
https://velog.io/@pyo-sh/Yarn-Berry-%ED%99%98%EA%B2%BD%EA%B3%BC-PnP-%EA%B8%B0%EB%8A%A5%EC%97%90%EC%84%9C-Prisma-%EC%82%AC%EC%9A%A9
Pnpify 와 OUTPUT설정을 통해서도 불가능할까요..?

**Comment by PracticeEveryday** [comment]
> https://velog.io/@pyo-sh/Yarn-Berry-%ED%99%98%EA%B2%BD%EA%B3%BC-PnP-%EA%B8%B0%EB%8A%A5%EC%97%90%EC%84%9C-Prisma-%EC%82%AC%EC%9A%A9 Pnpify 와 OUTPUT설정을 통해서도 불가능할까요..?

이 방법 될 수 있을 거 같습니다 제가 시도해서 PR 올려 볼게요!! :)

**Comment by PracticeEveryday** [comment]
![image](https://user-images.githubusercontent.com/97580759/236440445-49cd0269-b6a8-4c52-bde8-3ac24736d742.png)

해당 에러는 generated 된 폴더가 dist 파일안에 함께 컴파일 되지 않아 경로를 찾지 못하는 에러였습니다. ㅠ.ㅠ
generated된 폴더를 상단으로 옮기면서 경로를 찾을 수 있도록 처리한 뒤 PR 올렸습니다 :)

**Comment by stae1102** [comment]
yarn berry 때문에 prisma 세팅이 간단하지가 않군요 고생하셨습니다
